### PR TITLE
build: travis ci integration 

### PR DESCRIPTION
**Pull request by qnislavnachev**
Travis CI Integration 

Fixes #37

### CODE REVIEW

**Comment by qnislavnachev** [comment]
i ve tried to broke the commit but i still can push broken code

**Comment by qnislavnachev** [comment]
i ve tried to broke the commit but i still can push broken code

**Comment by mgenov** [comment]
As I can see no CI build is performed.

**Comment by mgenov** [comment]
This is how PR should look when CI is building it: 

screen shot 2017-01-27 at 9 43 19 am

I'm not sure, but maybe you have to merge configuration file of travis and after that to try to submit PR with broken test. 

Merging restriction need to be configured in the project settings.

**Comment by mgenov** [comment]
This is how configuration settings looks like on Git. 

screen shot 2017-01-27 at 9 46 11 am

I'll add it as configuration as immediately after you get CI server working as expected.

**Comment by qnislavnachev** [comment]
added a status to readme.md but still not sure this is all

**Comment by mgenov** [comment]
Readme.md is just for information, nothing more.

**Comment by qnislavnachev** [comment]
I read about that status checks but I wont create a check because the owner of the repository should create this: 

travis

and then when I create a pull request on the protected branch it would check I think

**Comment by mgenov** [comment]
It's added, force update your PR.

**Comment by mgenov** [comment]
Pending ....

**Comment by mgenov** [comment]
screen shot 2017-01-27 at 4 56 31 pm

**Comment by qnislavnachev** [comment]
now I see it create his checks

**Comment by mgenov** [comment]
```java
automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at com.clouway.nvuapp.adapter.persistence.ConnectionProvider.get(ConnectionProvider.java:18)
	at com.clouway.nvuapp.adapter.persistence.ConnectionProvider.get(ConnectionProvider.java:12)
	at com.clouway.nvuapp.adapter.persistence.dao.DataStore.update(DataStore.java:23)
	at com.clouway.nvuapp.adapter.persistence.TableManager.truncateTable(TableManager.java:17)
	at com.clouway.nvuapp.core.SessionRepositoryTest.setUp(SessionRepositoryTest.java:23)
```

You have a db issue as tests are unable to connect to the CI database.

**Comment by mgenov** [comment]
https://travis-ci.org/clouway-incubator/bank-t2/builds/195896169

**Comment by qnislavnachev** [comment]
Environment Variables are set up now JDBC can create his connection

**Pull request merged**
