### PR TITLE
nvuApp: quotes no longer available

### PR DESCRIPTION
**Pull request by qnislavnachev**
quotes no longer available in textfields when user create a questions

### CODE REVIEW

**Comment by qnislavnachev** [comment]
quotes are not available when user create a question, in the future I will think how gson can escape this

**Comment by qnislavnachev** [comment]
fixed tests now CI passes

**Comment by mgenov** [comment]
Paste a sample string that comes from the request as I'm still not sure that this is required.

**Comment by qnislavnachev** [comment]
double quotes now are available when the string comes from the request it replace it with cyrillic alphabet

**Pull request merged**
